### ISSUE TITLE
Question about the evaluation

### ISSUE THREAD

**Issue by Luolc** [DeepPavlov/convai#17]
Hi. I have a question about the evaluation of ConvAI2 competition.

In Section `PersonaChat ConvAI2 Dataset`, there mentioned `Evaluation will take place on both types of persona.`.
I think it means that you will evaluate submitted models on both `self_original` and `self_revised` data.

But, there is only one leaderboard, and only one number for a specific model and metric.
So what does the numbers mean? Is that an average of original and revised?

Besides, which dataset should we use for training? Do we need to train two separate models for different type of data?

**Comment by jaseweston** [comment]
Yes, we do plan to evaluate on both more for analysis reasons but at the moment we are evaluating on self_original only and that will be used to decide which models get to the human evaluation stage. Just to avoid confusion we will remove that text.  You are free to train on whatever you want (in the personachat paper we found training on revised actually gave marginally better results on original).
