### ISSUE TITLE
Data License

### ISSUE THREAD

**Issue by f11r** [DeepPavlov/convai#18]
I couldn't find a license wrt the data (neither for https://s3.amazonaws.com/fair-data/parlai/personachat/personachat.tgz nor for the `data` directory here). It would be great if you added one (or point me in the right direction if I missed it) so we know what usage outside of the competition are permitted.

**Comment by emilydinan** [comment]
Hello, you can find the license here: https://github.com/facebookresearch/ParlAI/blob/master/parlai/tasks/personachat/LICENSE_DOCUMENTATION

**Comment by f11r** [comment]
So I did miss it. Thank you!
