### ISSUE TITLE
Tickets for NIPS

### ISSUE THREAD

**Issue by thomwolf** [DeepPavlov/convai#27]
Hi all,
So like many people we couldn't get tickets for NIPS.
Do you know if there are tickets for the participant to the competition?
Best,
Thomas

**Comment by jaseweston** [comment]
I'm finding out..

**Comment by jaseweston** [comment]
Yes, can you give us your NIPS.cc related email? And we can get you a
workshop invite.

**Comment by Henry-E** [comment]
henry.elder2 (a t) mail.dcu.ie
